# Generated by Django 5.0.2 on 2024-03-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0013_customuser_email_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='new email address'),
        ),
    ]
